---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE
)
library(tidyverse)
```

<br>

PDF version available [here](./Kathleen_Hablutzel_Resume.pdf).

<br>

<br>

## Skills & Certifications

**Languages:** Python, JavaScript, R, Java, SQL

**Tools/Skills:** Angular, Git/GitHub, Agile Development, HTML5/CSS, Tableau, Gephi, ArcGIS, LaTeX, Adobe InDesign

**Bank of America Tech University Badges:** Python, Artificial Intelligence, Data Management Fundamentals

<br>

<br>

## Experience

<br>

### Global Technology Sophomore Summer Analyst
#### Bank of America, Corporate Treasury Data Horizontal Team
##### *June – Aug. 2021*, Charlotte, NC
* Automated joins and transformations of data tables in the Corporate Treasury data pipeline using Pandas DataFrames
in Python
* Translated Oracle SQL data mappings into Python API to replace existing third-party data management software
handling data integration for Bank of America’s three corporate lines of business

<br>

### Software Engineering Research Assistant
#### Smith College, STRIDE Research Program
##### *Sept. 2020 – Present*, Northampton, MA

* Drive implementation of automatic goal model merging in web-based requirements engineering goal modeling tool, [BloomingLeaf](https://github.com/amgrubb/BloomingLeaf)
* Foster Agile development practices employing Jira boards and weekly sprint planning meetings
* Refactored frontend model management features using JavaScript, JQuery, JSON, and HTML/CSS
* Research Assistantship in the Grubb Software Engineering Lab

<br>

### Algorithms Teaching Assistant
#### Smith College
##### *Feb. 2021 — Present*, Northampton, MA

* Tutor students in theory and implementation of common algorithms and algorithmic design techniques
* Selected as the first TA for Smith's new Applied Algorithms course in Spring 2021

<br>

### Data Fellow, Cynthia Wallace for Congress
#### Bluebonnet Data
##### *June – November 2020*, Charlotte, NC
* Performed tactical field analytics for Cynthia Wallace’s campaign in the NC-09 Congressional District
* Identified over 2000 potential donors from publicly available data sources using the Python BeautifulSoup4 library
* Visualized demographic trends in the district using the ggplot2, sf, and leaflet packages in R

<br>

### Data Science Policy Research Assistant
#### Smith College, STRIDE Research Program
##### *Sept. 2019 – Sept. 2020*, Northampton, MA

* Explored the history and politics of data science and tech industry, with a particular focus on the relationship between data and power, under Professor Brent Durbin
* Investigated use of facial recognition systems for data-driven surveillance, with a focus on China and the US

<br>

### Program Assistant
#### Summer Research & Innovation Program
#### North Carolina School of Science and Mathematics (NCSSM)
##### *June – Aug. 2019, 2020*, Durham, NC
*	Developed repeatable curriculum for an R Data Science Bootcamp, including data visualization and data wrangling
*	Led redesign of the website architecture of the Research & Innovation Google Site
*	Built Python script to format 153 student projects into HTML5 website backbone for student research showcase

<br>

### Intern, Zavlanos Robotics Laboratory
#### Duke University + NCSSM Research in Computational Sciences Program
##### *June – Aug. 2018*, Durham, NC
*	Implemented gradient descent optimization algorithms in MATLAB for sparse complex matricies
* Built edge detection programs in Python with OpenCV

<br>

<br>

## Education

<br>

### Smith College '23

#### Majors in Computer Science & Statistical and Data Sciences

* 4.0/4.0 GPA
* **Zollman Scholarship:** Smith’s highest academic scholarship, awarded to fewer than 10 entering first-year students
* **STRIDE Research Program:** Selective paid research assistant program, investigating data science policy
* **Relevant Coursework:** Algorithms, Machine Learning, Network Security, Communicating with Data, Data Structures, Intro Data Science, Linear Algebra, Multiple Regression, Research Design & Analysis, Theory of Computation

<br>

### North Carolina School of Science and Mathematics '19

* 4.79/4.0 GPA
* **Research in Computational Science Program:** Trained in R, Python, MATLAB, supercomputing, and other tools
* **Mathematics Department Award:** For excellence in 10 math courses and numerous mathematical modeling projects
* **Mathematics Teaching Assistant:** Senior leadership position tutoring peers in Multivariable Calculus and other math

<br>

<br>


## Awards

* **Best in Design**, HackSmith 2021 for the [Unconventional Knitting Pattern Generator](https://krhablutzel.github.io/KnittingPatternGenerator/)
*	**Honorable Mention**, [2020 Fall Undergraduate Statistics Class Project Competition](https://www.causeweb.org/usproc/usclap/2020/fall/winners), Intermediate Statistics
*	Arthur Ellis Hamm Prize **Winner**
*	Smith College **Dean’s List** 2019-2020
*	**Technical Computing Scholarship Award**, [MathWorks Math Modeling Challenge](https://m3challenge.siam.org/archives/2019/winning-solutions)
*	**Outstanding Winner** and **National Council of Teachers of Mathematics Winner**, [High School Mathematical Contest in Modeling](https://www.comap.com/highschool/contests/himcm/2018results.html)

<br>

<br>

## Activities & Leadership

**Smith Computer Science Department Liaison:** Runs weekly CS community programming including interview prep, mini hackathons, and financial literacy sessions. Communicates opportunities to the Smith CS community. Represents and advocates for CS student interests at CS faculty meetings.

**Haven-Wesley House Council:** Coordinates house community-building activities as the junior class representative in my residential community at Smith College.

**Workday User Acceptance Testing (UAT) Assistant:** Evaluated Workday Student system rollout from user perspective and suggested critical design considerations

**The Amplifier Project Web Developer:** Built the virtual stage for Smith College Theater's Fall 2020 production

**Smithies in Statistical and Data Sciences Treasurer:** Managed funds and organized department student/faculty lunches

**Props Internship:** Led props design and construction for multiple Smith College theatrical productions

**Reacting to the Past:** Negotiated support for historical legislation via debate and persuasive public speaking

**Publication Editor-in-Chief, Broad Street Scientific & Fifth World:** Managed publication of 2 student research journals from concept to final production

**TEDx Committee Chairperson:** Coordinated 100-person TEDx conference with 5 speakers


<br>

<br>

## Other Interests

Cryptography, Running, Knitting, Theater, 16^th^ Century British Politics
